kind: Pod
apiVersion: v1
metadata:
  name: green-app
  namespace: psc-exemplos
  labels:
    app: green-app
    clustergroup: psc-cluster-grp-01
spec:
  containers:
    - name: green-app
      image: hashicorp/http-echo
      args:
        - "-text=green"

---

kind: Service
apiVersion: v1
metadata:
  name: green-service
  namespace: psc-exemplos
spec:
  selector:
    app: green-app
  ports:
    - port: 5678 # Default port for image
